# Generated by Django 3.1.5 on 2021-01-11 15:55

import deceased.helpers
import django.contrib.postgres.indexes
from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0002_pg_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='tcm-test-989aa9b5-319a-470e-876c-d9ba2131c1c1', default_acl='publicRead'), upload_to=deceased.helpers.get_image_path),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='message',
            field=models.TextField(blank=True, max_length=480, null=True),
        ),
        migrations.AddIndex(
            model_name='deceased',
            index=django.contrib.postgres.indexes.GistIndex(fields=['name', 'country', 'city'], name='deceased_gist', opclasses=['gist_trgm_ops', 'gist_trgm_ops', 'gist_trgm_ops']),
        ),
    ]
