# Generated by Django 3.1.5 on 2021-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0005_generate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='code',
            field=models.CharField(default='UoYUnzmmW5k', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='message',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
