# Generated by Django 3.1.5 on 2021-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0007_generate_slugs2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=240),
        ),
    ]
