# Generated by Django 3.1.5 on 2021-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0008_auto_20210113_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
