# Generated by Django 3.1.5 on 2021-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceased', '0010_auto_20210118_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deceased',
            name='occupation',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
